import { StyleSheet } from "react-native";
import { COLORS } from "../../../Common/CommonColors";

export default StyleSheet.create({
    modalContainer: {
        width: "100%",
        height: "100%",
        alignItems: 'center',
        justifyContent: 'center',
    },
    container: {
        backgroundColor: COLORS.backgroundLight,
        height: "90%",
        marginTop: "10%",
        borderRadius: 25,
        marginHorizontal: 10,
        paddingHorizontal: 20,
        paddingBottom: 20,
        shadowColor: COLORS.Black,
        shadowOpacity: 0.5,
        shadowOffset: { width: 4, height: 4},
        elevation: 5,
    },
    scrollViewContainer: {
        display: 'flex',
        width: "100%",
        height: "100%",
        marginBottom: 55,
    },
    returnButton : {
        alignItems: 'center',
        justifyContent: 'center',
        width: "100%",
        height: 30,
    },
    buttonsContainer: {
        display: 'flex',
        flexDirection: 'row',
        width: "100%",
        alignItems: 'center',
        justifyContent: 'space-between',
        position: 'absolute',
        bottom: 20,
        left: 20,
    },
    button: {
        backgroundColor: COLORS.clickableColor,
        color: COLORS.background,
        height: 45,
        width: "48%",
        justifyContent: 'center',
        borderRadius : 17,
    },
    title: {
        fontSize: 30,
        fontWeight: '800',
        color: COLORS.foreground,
        textAlign: 'center',
    },
    author: {
        fontSize: 16,
        fontWeight: '800',
        color: COLORS.foregroundHolder,
        textAlign: 'center', 
        marginTop: 15,     
        marginBottom: 20,
    },
    text: {
        fontSize: 14,
        fontWeight: '800',
        color: COLORS.foreground,
        textAlign: 'left',
        marginTop: 5,
        marginBottom: 20,
    },
    textNumber: {
        fontSize: 30,
        fontWeight: '800',
        color: COLORS.foreground,
        textAlign: 'left',
    },
    statsContainer: {
        display: 'flex',
        flexDirection: 'row',
        width: "100%",
        justifyContent: 'space-between',
        alignItems: 'center',
        marginTop: 5,
        marginBottom: 20,
    },
    textHolder: {
        fontSize: 13,
        fontWeight: '800',
        color: COLORS.foregroundHolder,
        textAlign: 'left',
        marginRight: 20,
    },
    tagsContainer: {
        marginTop: 5,
        marginBottom: 20,
    },
    readingsContainer: {
        marginTop: 5,
        marginBottom: 20,
    },
});