import { StyleSheet } from "react-native";
import { COLORS } from "../../../library/CommonColors";

export default StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: COLORS.background,
        alignItems: 'center',
        justifyContent: 'center',
    },
    scrollViewContainer: {
        width: '100%',
        marginBottom: 65,
        marginTop: 60,
    },
    returnButton : {
        position: 'absolute',
        alignItems: 'center',
        justifyContent: 'center',
        width: "100%",
        top: -40,
    },
    buttonsContainer: {
        display: 'flex',
        flexDirection: 'row',
        width: "100%",
        alignItems: 'center',
        justifyContent: 'space-between',
        position: 'absolute',
        bottom: 10,
        paddingHorizontal: 10,
    },
    button: {
        backgroundColor: COLORS.clickableColor,
        color: COLORS.background,
        height: 45,
        width: "48%",
        justifyContent: 'center',
        borderRadius : 40,
        shadowColor: COLORS.Black,
        shadowOpacity: 0.5,
        shadowOffset: { width: 4, height: 4},
        elevation: 5,
    },
    title: {
        paddingHorizontal: 10,
        fontSize: 35,
        fontWeight: '800',
        color: COLORS.foreground,
        textAlign: 'center',
    },
    author: {
        fontSize: 16,
        fontWeight: '800',
        color: COLORS.foregroundHolder,
        textAlign: 'center', 
        marginTop: 15,     
        marginBottom: 15,
    },
    description: {
        paddingHorizontal: 10,
        fontSize: 14,
        fontWeight: '800',
        color: COLORS.foreground,
        textAlign: 'left',
        marginTop: 5,
        marginBottom: 15,
    },
    textNumber: {
        fontSize: 30,
        fontWeight: '800',
        color: COLORS.foreground,
        textAlign: 'left',
    },
    statsContainer: {
        paddingHorizontal: 10,
        display: 'flex',
        flexDirection: 'row',
        width: "100%",
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 15,
    },
    textHolder: {
        paddingHorizontal: 10,
        fontSize: 13,
        fontWeight: '800',
        color: COLORS.foregroundHolder,
        textAlign: 'left',
        marginRight: 10,
    },
    tagsContainer: {
        marginTop: 5,
        marginHorizontal: 10,
        marginBottom: 15,
    },
    readingsContainer: {
        width: "100%",
        paddingHorizontal: 10,
        marginTop: 5,
    },
});